apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8snet
  namespace: default
  labels:
    name: k8snet
spec:
  template:
    metadata:
      labels:
        name: k8snet
    spec:
      hostNetwork: true
      containers:
      - name: k8sconntracker
        image: dongyiyang/k8sconntracker:dev
        securityContext:
          privileged: true
        ports:
          - name: http
            containerPort: 2222
            hostPort: 2222
        command:
          - /bin/conntracker
        args:
          - --v=3
          - --kubeconfig=/etc/kubeturbo/admin.kubeconfig
        volumeMounts:
        - name: vmt-config
          mountPath: /etc/kubeturbo
          readOnly: true
      restartPolicy: Always
      serviceAccount: turbo-user
      volumes:
      - name: vmt-config
        secret:
          secretName: vmt-config
